### ISSUE TITLE
A question about the memory usage and strange error when running the code

### ISSUE THREAD

**Issue by andyclsr** [srzer/MOD#1]
Hi, thanks for your wonderful work and your kindness for opensourcing the code!
I tried to run the code but failed encountering 2 problems belows. 
First is the huge memory usage used by MOD. I did not try to check how much it will consume at maximum but I am sure it is more than 50G compared to 20G comsumed by 7b model load in 8bit when inferencing. It is normal?

Second is the strange error like this. I don't know whether it is related with OOM problem.
<img width="1567" alt="截屏2024-10-09 15 42 30" src="https://github.com/user-attachments/assets/2347cb86-c2a3-4ba8-85cf-15ca4aaa907d">

RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

Look forward to your early reply! Thanks anyway.

**Comment by srzer** [comment]
Hi, could you check that whether you can run smoothly when only using one model to inference? That would help debug!
Yeah, I think the second error is caused by the first.

**Comment by srzer** [comment]
And could you provide more details about your experiments?

**Comment by andyclsr** [comment]
Great thanks for your prompt reply! I follow your advice and found another error, and I think maybe it is related to the versions of packages(as I did not fully follow the requirement.txt) including torch. Will it be a major factor? 
<img width="1691" alt="截屏2024-10-09 16 36 33" src="https://github.com/user-attachments/assets/f046277c-f39a-4b40-9375-61f3c99f9091">

I have trained 2 ppo model and now try to conduct "ppo/eval_ours.sh".

**Comment by srzer** [comment]
Thanks! I have met the `AttributeError` before, and it was induced by inconsistency of `transformers`'s version. You could try the `transformer` version we recommend in README.

**Comment by andyclsr** [comment]
Really great thanks for your precise advice! I solved the problem by using the version of transformers you recommended. 
But, when I changed back to the setting involving 2 ppo trained models, the OOM problem seems to still exist as the error report mentioned before.
what is the memory overhead in your experiment? Do I need 80G for the experiment(now I am using about 50G)?

**Comment by srzer** [comment]
It should make not much difference for 2 models since we use LoRA adapters. So it is not expected that the overhead incerase to >50G. So I am not sure what causes the error right now.
Do you know which is the first line that the OOM issue appears?

**Comment by andyclsr** [comment]
Thanks for your patient response! I checked it again and it is 43~46G consumption and the highest cost 50G in gpu0 due to Accelerate. And as you mentioned, Lora is a small cost, and therefore 2 or 1 model cost nearly the same. I think the main problem of this high usage is the sft model not loaded in 8-bit or bf16. Did you try this before? I wonder how much performance difference will it cause.

**Comment by srzer** [comment]
Sorry I've not checked that. Our experiments can be conducted on A6000 card.

**Comment by andyclsr** [comment]
No need to apologize, I really appreciate your response! Thanks again for all the patient and prompt response! : )
